#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parcial2_Grupo6
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="TP2_GRUPO6")]
	public partial class DataLinqClassDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertalumno(alumno instance);
    partial void Updatealumno(alumno instance);
    partial void Deletealumno(alumno instance);
    partial void Insertcomentario(comentario instance);
    partial void Updatecomentario(comentario instance);
    partial void Deletecomentario(comentario instance);
    #endregion
		
		public DataLinqClassDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["TP2_GRUPO6ConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataLinqClassDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataLinqClassDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataLinqClassDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataLinqClassDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<alumno> alumnos
		{
			get
			{
				return this.GetTable<alumno>();
			}
		}
		
		public System.Data.Linq.Table<comentario> comentarios
		{
			get
			{
				return this.GetTable<comentario>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.alumnos")]
	public partial class alumno : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _dni_alumno;
		
		private string _nombre_alumno;
		
		private string _apellido_alumno;
		
		private string _email_alumno;
		
		private string _turno_alumno;
		
		private EntityRef<comentario> _comentario;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ondni_alumnoChanging(int value);
    partial void Ondni_alumnoChanged();
    partial void Onnombre_alumnoChanging(string value);
    partial void Onnombre_alumnoChanged();
    partial void Onapellido_alumnoChanging(string value);
    partial void Onapellido_alumnoChanged();
    partial void Onemail_alumnoChanging(string value);
    partial void Onemail_alumnoChanged();
    partial void Onturno_alumnoChanging(string value);
    partial void Onturno_alumnoChanged();
    #endregion
		
		public alumno()
		{
			this._comentario = default(EntityRef<comentario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dni_alumno", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int dni_alumno
		{
			get
			{
				return this._dni_alumno;
			}
			set
			{
				if ((this._dni_alumno != value))
				{
					this.Ondni_alumnoChanging(value);
					this.SendPropertyChanging();
					this._dni_alumno = value;
					this.SendPropertyChanged("dni_alumno");
					this.Ondni_alumnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre_alumno", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nombre_alumno
		{
			get
			{
				return this._nombre_alumno;
			}
			set
			{
				if ((this._nombre_alumno != value))
				{
					this.Onnombre_alumnoChanging(value);
					this.SendPropertyChanging();
					this._nombre_alumno = value;
					this.SendPropertyChanged("nombre_alumno");
					this.Onnombre_alumnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellido_alumno", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string apellido_alumno
		{
			get
			{
				return this._apellido_alumno;
			}
			set
			{
				if ((this._apellido_alumno != value))
				{
					this.Onapellido_alumnoChanging(value);
					this.SendPropertyChanging();
					this._apellido_alumno = value;
					this.SendPropertyChanged("apellido_alumno");
					this.Onapellido_alumnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email_alumno", DbType="VarChar(60) NOT NULL", CanBeNull=false)]
		public string email_alumno
		{
			get
			{
				return this._email_alumno;
			}
			set
			{
				if ((this._email_alumno != value))
				{
					this.Onemail_alumnoChanging(value);
					this.SendPropertyChanging();
					this._email_alumno = value;
					this.SendPropertyChanged("email_alumno");
					this.Onemail_alumnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_turno_alumno", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string turno_alumno
		{
			get
			{
				return this._turno_alumno;
			}
			set
			{
				if ((this._turno_alumno != value))
				{
					this.Onturno_alumnoChanging(value);
					this.SendPropertyChanging();
					this._turno_alumno = value;
					this.SendPropertyChanged("turno_alumno");
					this.Onturno_alumnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="alumno_comentario", Storage="_comentario", ThisKey="dni_alumno", OtherKey="dni_alumno", IsUnique=true, IsForeignKey=false)]
		public comentario comentario
		{
			get
			{
				return this._comentario.Entity;
			}
			set
			{
				comentario previousValue = this._comentario.Entity;
				if (((previousValue != value) 
							|| (this._comentario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._comentario.Entity = null;
						previousValue.alumno = null;
					}
					this._comentario.Entity = value;
					if ((value != null))
					{
						value.alumno = this;
					}
					this.SendPropertyChanged("comentario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.comentarios")]
	public partial class comentario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _dni_alumno;
		
		private string _apellido_alumno;
		
		private string _comentario_alumno;
		
		private EntityRef<alumno> _alumno;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ondni_alumnoChanging(int value);
    partial void Ondni_alumnoChanged();
    partial void Onapellido_alumnoChanging(string value);
    partial void Onapellido_alumnoChanged();
    partial void Oncomentario_alumnoChanging(string value);
    partial void Oncomentario_alumnoChanged();
    #endregion
		
		public comentario()
		{
			this._alumno = default(EntityRef<alumno>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dni_alumno", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int dni_alumno
		{
			get
			{
				return this._dni_alumno;
			}
			set
			{
				if ((this._dni_alumno != value))
				{
					if (this._alumno.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ondni_alumnoChanging(value);
					this.SendPropertyChanging();
					this._dni_alumno = value;
					this.SendPropertyChanged("dni_alumno");
					this.Ondni_alumnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellido_alumno", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string apellido_alumno
		{
			get
			{
				return this._apellido_alumno;
			}
			set
			{
				if ((this._apellido_alumno != value))
				{
					this.Onapellido_alumnoChanging(value);
					this.SendPropertyChanging();
					this._apellido_alumno = value;
					this.SendPropertyChanged("apellido_alumno");
					this.Onapellido_alumnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comentario_alumno", DbType="VarChar(200)")]
		public string comentario_alumno
		{
			get
			{
				return this._comentario_alumno;
			}
			set
			{
				if ((this._comentario_alumno != value))
				{
					this.Oncomentario_alumnoChanging(value);
					this.SendPropertyChanging();
					this._comentario_alumno = value;
					this.SendPropertyChanged("comentario_alumno");
					this.Oncomentario_alumnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="alumno_comentario", Storage="_alumno", ThisKey="dni_alumno", OtherKey="dni_alumno", IsForeignKey=true)]
		public alumno alumno
		{
			get
			{
				return this._alumno.Entity;
			}
			set
			{
				alumno previousValue = this._alumno.Entity;
				if (((previousValue != value) 
							|| (this._alumno.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._alumno.Entity = null;
						previousValue.comentario = null;
					}
					this._alumno.Entity = value;
					if ((value != null))
					{
						value.comentario = this;
						this._dni_alumno = value.dni_alumno;
					}
					else
					{
						this._dni_alumno = default(int);
					}
					this.SendPropertyChanged("alumno");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
